

###post data from server
POST http://localhost:8000/api/v1/tasks
#header of the request
Content-Type: application/json

#Body of the request
{
    "task":"cleaning",
    "hr":14,
    "type":"entry"
}


### get data from database
GET http://localhost:8000/api/v1/tasks


### delete data from database
DELETE http://localhost:8000/api/v1/tasks
#header of request
Content-Type: application/json

#Body of request
{
    "_id":"662522f22b6e7853cd74a631"
}



###update data in the server
PATCH http://localhost:8000/api/v1/tasks
#header of request
Content-Type: application/json

#Body of request
{
    "id":"662522f22b6e7853cd74a631",
    "type":"bad"
}